language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

env:
  - TESTBENCH_VERSION=3.1.*

matrix:
  include:
    - php: 5.6
      env: TESTBENCH_VERSION=3.1.*
    - php: 5.6
      env: TESTBENCH_VERSION=3.2.*
    - php: 7.1
      env: TESTBENCH_VERSION=3.1.*
    - php: 7.1
      env: TESTBENCH_VERSION=3.2.*
    - php: 7.1
      env: TESTBENCH_VERSION=3.3.*
    - php: 7.1
      env: TESTBENCH_VERSION=3.4.*
    - php: 7.1
      env: TESTBENCH_VERSION=3.5.*
    - php: 7.1
      env: TESTBENCH_VERSION=3.6.*
    - php: nightly
      env: TESTBENCH_VERSION=3.4.*
    - php: nightly
      env: TESTBENCH_VERSION=3.5.*
    - php: nightly
      env: TESTBENCH_VERSION=3.6.*

before_install:
  - composer require "orchestra/testbench:${TESTBENCH_VERSION}" --no-update

install:
  - composer update --prefer-source --no-interaction

script: ./vendor/bin/phpunit --configuration phpunit.xml --coverage-clover ./tests/logs/clover.xml
